drop table if exists member cascade;

create table member (
  id bigint generated by default as identity,
  name varchar(255),
  primary key (id)
);

drop table if exists comment cascade;

create table comment (
  id bigint generated by default as identity,
  content varchar(1000),
  date varchar(200),
  likes bigint,
  primary key (id)
);